name: publishing-libraries
description: A simple pipeline for publishing angular libraries do github npm
branding: 
  icon: check-square
  color: red
run-name: ${{ github.actor }} is publishing libraries to private registry
on:
  release:
    types: [published]
jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN_GITHUB_REGISTRY }}
      - name: Autenticação
        run: |
          git config --global user.email "${{github.actor}}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
      - name: Criar tag no Git
        run: git tag -a v${{ github.event.release.tag_name }} -m "Release ${{ github.event.release.tag_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Push da tag para o GitHub
        run: git push origin v${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  publishing-libraries:
    runs-on: ubuntu-latest
    needs: tag_release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Autenticação
        run: |
            git config --global user.email "${{github.actor}}@users.noreply.github.com"
            git config --global user.name "${{ github.actor }}"
      - run: |
          npm install
          npm ci
          npm config set registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.TOKEN_GITHUB_REGISTRY }}
          npm version major
          npm publish